name: updateConfigFile
description: |
  update Config File

# Find all repositories that contain the `fmt.Sprintf` statement using structural search
on:
  - repositoriesMatchingQuery: file:package.json author patterntype:regex

steps:
  # Run Comby (https://comby.dev) to replace the Go statements...
  - run: |
      comby -in-place '"author":"Kaustubh"' '"author": "Shreyal",' package.json
    container: comby/comby


# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: Upgrade all repos node version to 2.0.0
  body: Upgrade all repos node version to 3.4.0
  branch: batches/versionUpgrade
  commit:
    message: Upgrade all repos lib1 version to 3.4.0
